[project]
name = "iv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=9.5.0",
    "jupyter>=1.1.1",
    "pandas>=2.3.2",
    "plotly>=6.3.0",
    "streamlit>=1.50.0",
    "tqdm>=4.67.1",
]
